-- Add commercial trip fields introduced in schema.prisma
ALTER TABLE "Trip"
ADD COLUMN IF NOT EXISTS "isCommercial" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "price" DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS "childPrice" DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS "maxCapacity" INTEGER,
ADD COLUMN IF NOT EXISTS "currentParticipants" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS "bookingDeadline" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "termsAndConditions" TEXT;